#!/bin/sh
#
# Wrapper around inotifywait to run tests on file changes.
# If a test file changes, only this file is run, otherwise the whole test suite.
#
# The recommended way to run it is via `make testwatch`, or `make testwatchx`
# (to exit on first failure).
#
# The default run command is "make %s" (where %s is # replaced with the test
# file), and can be given as first argument.
#
# You can specify VADER_OPTIONS=-x to exit on the first test failure:
#     VADER_OPTIONS=-x contrib/run-tests-watch
# Or
#     contrib/run-tests-watch 'make %s VADER_OPTIONS=-x'

watch="autoload plugin tests"
echo "Watching: $watch"

if [ -n "$1" ]; then
  cmdpattern="$1"
else
  cmdpattern="make %s VADER_OPTIONS=$VADER_OPTIONS"
fi

title() {
  printf '\e]1;%s\a' "$*"
  printf '\e]2;%s\a' "$*"
}

# Recursively kill childs - required to get out of a running pdb.
kill_with_childs() {
  for p in $(pgrep -P "$1"); do
    kill_with_childs "$p"
  done
  kill "$1"
}

pid=
output=
set -x
set -e
while true; do
  # reset
  if [ -n "$output" ]; then
    echo "================================================================="
    # echo "$output"
    testfiles="$output"
  else
    testfiles='tests/neomake.vader'
  fi

  if [ -n "$pid" ] && kill -0 "$pid" 2>/dev/null; then
    echo 'Killing previous run…'
    kill_with_childs "$pid"
  fi

  # shellcheck disable=SC2059
  cmd=$(printf "$cmdpattern" "$testfiles")
  title "… $cmd"
  # shellcheck disable=SC2015
  ($cmd && title "✔ $cmd" || title "✘ $cmd") </dev/tty &
  pid=$!

  sleep 1
  # shellcheck disable=SC2086
  output="$(inotifywait -r -e close_write \
    --exclude '/(__pycache__/|\.)|.*\.neomaketmp_.*' \
    --format '%w%f' $watch)"
done
