#!/bin/sh -x
#
# Wrapper around inotifywait to run tests on file changes.
# If a test file changes, only this file is run (first), while whole test suite
# is run afterwards (and initially).
#
# The recommended way to run it is via `make testwatch`, or `make testwatchx`
# (to exit on first failure).
#
# # Internal documentation:
#   The default run command is "make %s" (where %s gets replaced with the test
#   file(s)), and can be given as first argument.
#
#   You can specify VADER_OPTIONS=-x to exit on the first test failure:
#       VADER_OPTIONS=-x contrib/run-tests-watch
#   or use the following:
#       contrib/run-tests-watch 'make %s VADER_OPTIONS=-x'

watch="autoload plugin tests"
echo "Watching: $watch"

if [ -n "$1" ]; then
  cmdpattern="$1"
else
  cmdpattern="make %s VADER_OPTIONS='$VADER_OPTIONS'"
fi

title() {
  printf '\e]1;%s\a' "$*"
  printf '\e]2;%s\a' "$*"
}

status_file=$(mktemp)
handle_cmd_result() {
  if [ "$1" = 0 ]; then
    title "✔ $2"
    if [ "${2#*${alltestsfile}*}" != "$2" ]; then
      alltests_succeeded=1
    fi
  else
    title "✘ $2"
    if [ "${2#*${alltestsfile}*}" != "$2" ]; then
      alltests_succeeded=0
    fi
  fi
  echo "$alltests_succeeded" > "$status_file"
}

# Recursively kill childs - required to get out of a running pdb.
kill_with_childs() {
  for p in $(pgrep -P "$1"); do
    kill_with_childs "$p"
  done
  if kill -0 "$1" 2>/dev/null; then
    kill "$1" || true
  fi
}

alltestsfile='tests/neomake.vader'
alltests_succeeded=0
pid=
output=
set -e
last_changed_testsfile="$alltestsfile"

while true; do
  # reset
  testfiles="$last_changed_testsfile"
  if [ -n "$output" ]; then
    # There was a previous run
    echo "================================================================="
    echo "changed file: $output"

    read -r alltests_succeeded < "$status_file" || alltests_succeeded=0

    if [ "${output#tests/}" != "$output" ]; then
      last_changed_testsfile="$output"
      testfiles="$output"
      # Run full tests afterwards (if it has not succeeded before).
      if [ "$output" != "$alltestsfile" ]; then
        if [ "$alltests_succeeded" = 0 ]; then
          testfiles="$testfiles $alltestsfile"
        fi
      fi
    else
      alltests_succeeded=0
      testfiles="$alltestsfile"
    fi

    if [ -n "$pid" ] && kill -0 "$pid" 2>/dev/null; then
      echo 'Killing previous run…'
      kill_with_childs "$pid"
    fi
  fi

  # shellcheck disable=SC2059
  cmd="$(printf "$cmdpattern" "$testfiles")"
  echo "Running $cmd"
  title "… $testfiles"
  # shellcheck disable=SC2015
  (set +e; eval "$cmd"; handle_cmd_result "$?" "$testfiles") </dev/tty &
  pid=$!

  sleep 1
  # shellcheck disable=SC2086
  output="$(inotifywait -r -e close_write \
    --exclude '/(__pycache__/|\.)|.*\@neomake_.*' \
    --format '%w%f' $watch)"
done
