filetype off
set runtimepath+=vader
set runtimepath+=..
filetype plugin on
syntax enable
set hidden

set colorcolumn=75

" Easier for window numbers (incrementing).
set splitbelow

" No '-- More --' prompt, which would hang Travis.
set nomore
